### ISSUE TITLE
remove deprecated .error replacing with .fail 

### ISSUE THREAD

**Issue by aric87** [jayzamazing/Music-Quiz-App#6]
done will run whether there's success or error.

https://github.com/jayzamazing/Music-Quiz-App/blob/master/js/app.js#L259

**Comment by jayzamazing** [comment]
I am not sure I agree with this issue as per http://api.jquery.com/jquery.ajax/. I will agree that I probably should not use .error as per the following: "Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead". As far as I understand the documentation, .always which replaces .complete is what will always run as per http://api.jquery.com/deferred.always/ : "Add handlers to be called when the Deferred object is either resolved or rejected.". As per http://api.jquery.com/deferred.done/ .done() is only called when "when the Deferred object is resolved.". And the same thing for .fail() which is only called when "the Deferred object is rejected.". I could use .then but that is really just a combination of .done() and .fail() "jqXHR.then(function( data, textStatus, jqXHR ) {}, function( jqXHR, textStatus, errorThrown ) {});
Incorporates the functionality of the .done() and .fail() methods, allowing (as of jQuery 1.8) the underlying Promise to be manipulated. Refer to deferred.then() for implementation details."
I can agree at this time to stop using .error since it is deprecated, but need more clarification as to your comment on .done() unless you are saying that .done() should be replaced with .then().

**Comment by aric87** [comment]
When I wrote this, i was under the impression that done worked like always. looks like the docs disagree, and it works more like .then(). I'm not 100% on how jQuery uses .then, but with ES6 promises, then only fires for resolve conditions, and catch only fires for reject conditions, unless then is after catch, in which case it acts like .always

based on the jQuery docs you presented, then takes 2 callback functions (done, catch) or you can leave them seperate with done and catch. Up to you how you want to implement. Sorry for the mix up

**Comment by jayzamazing** [comment]
Yeah what you said makes sense. I will change this to remove deprecated .error replacing with .fail and wrap this up in the next push.

**Comment by jayzamazing** [comment]
Fixed in https://github.com/jayzamazing/Music-Quiz-App/pull/16.
